const data = {
    "/index.html": {
        "ko": {
            "moldtitle": "곰팡이 키우기",
            "about-sub": "시너지의 폭발",
            "about-text":
                "Hyper Hole는 게임 제작의 중심에서 최고의 창의력을 끌어내는 스튜디오입니다. 다양한 기술이 조합되어 빅뱅을 일으키듯, Hyper Hole은 팀워크를 통해 놀라운 게임을 탄생시킵니다. 우리는 우주의 퀘이사처럼 빛나는 게임을 만들기 위해, 초거대 블랙홀처럼 강력한 협업을 추구합니다. Hyper Hole에서 모든 팀원이 하나 되어 최고의 게임을 창조합니다.",
            "maintext": "Hyper Hole의 로고는 다양한 기술과 팀워크의 시너지가 모여 최고의 게임을 만들기 위한 우리의 무한한 에너지를 상징합니다. 퀘이사의 강렬한 폭발처럼, 우리의 게임과 로고는 창의력과 조화의 결과로 탄생한 빛나는 경험을 제공합니다. ",
            "gametext": "Hyper Hole는 게임 제작의 중심에서 최고의 창의력을 끌어내는 스튜디오입니다. 다양한 기술이 조합되어 빅뱅을 일으키듯, Hyper Hole은 팀워크를 통해 놀라운 게임을 탄생시킵니다. ",
        },
        "en": {
            "moldtitle": "Mold Farm",
            "about-sub": "explosion of synergy",
            "about-text":
                "Hyper Hole is a studio that brings out the best creativity at the heart of game development. Just as various substances combine to create the Big Bang, Hyper Hole brings together diverse individuals to create amazing games. To create games that shine like quasars in the universe, we pursue powerful collaboration, like a supermassive black hole. At Hyper Hole, every team member unites to create the best games.",
            "maintext": "The Hyper Hole logo symbolizes the explosive synergy of diverse skills and teamwork, much like the radiant burst of a quasar. Just as a quasar explodes with energy, our games offer brilliant experiences born from creativity and collaboration. The logo represents our boundless energy and our pursuit of creating the best games.",
            "gametext": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magn",
        },
    },

    "/html/privacypolicy.html": {
        "ko": {
            "pp_title": "개인정보 처리방침",
            "policy-intro": "",
            "policy-ar1": "",
            "policy-ar1-main": "",
            "policy-ar1-sub": "",
            "policy-ar2": "",
            "policy-ar2-main": "",
            "policy-ar2-sub1": "",
            "policy-ar2-sub2": "",
            "policy-ar2-sub3": "",
            "policy-ar2-sub4": "",
            "policy-ar3": "",
            "policy-ar3-main1": "",
            "policy-ar3-main2": "",
            "policy-ar3-main3": "",
            "policy-ar3-main4": "",
            "policy-ar3-main5": "",
            "policy-ar3-main6": "",
            "policy-ar3-main7": "",
            "policy-ar3-main8": "",
            "policy-ar3-main9": "",
            "policy-ar4": "",
            "policy-ar4-main1": "",
            "policy-ar4-main2": "",
            "policy-ar5": "",
            "policy-ar5-main1": "",
            "policy-ar5-main2": "",
            "policy-ar5-main3": "",
            "policy-ar5-main4": "",
            "policy-ar5-main5": "",
            "policy-ar6": "",
            "policy-ar6-main1": "",
            "policy-ar6-main2": "",
            "policy-ar6-main3": "",
            "policy-ar6-main4": "",
            "policy-ar6-main5": "",
            "policy-ar7": "",
            "policy-ar7-main": "",
            "policy-ar7-t1": "",
            "policy-ar7-t2": "",
            "policy-ar7-t3": "",
            "policy-ar7-t4": "",
            "policy-ar7-sub1": "",
            "policy-ar7-sub2": "",
            "policy-ar7-sub3": "",
            "policy-ar7-sub4": "",
            "policy-ar7-sub5": "",
            "policy-ar7-sub6": "",
            "policy-ar7-sub7": "",
            "policy-ar7-sub8": "",
            "policy-ar7-sub9": "",
            "policy-ar7-sub10": "",
            "policy-ar8": "",
            "policy-ar8-main1": "",
            "policy-ar8-main2": "",
        },

        "en": {
            "pp_title": "Personal Information Collection Policy",
            "policy-intro": "",
            "policy-ar1": "",
            "policy-ar1-main": "",
            "policy-ar1-sub": "",
            "policy-ar2": "",
            "policy-ar2-main": "",
            "policy-ar2-sub1": "",
            "policy-ar2-sub2": "",
            "policy-ar2-sub3": "",
            "policy-ar2-sub4": "",
            "policy-ar3": "",
            "policy-ar3-main1": "",
            "policy-ar3-main2": "",
            "policy-ar3-main3": "",
            "policy-ar3-main4": "",
            "policy-ar3-main5": "",
            "policy-ar3-main6": "",
            "policy-ar3-main7": "",
            "policy-ar3-main8": "",
            "policy-ar3-main9": "",
            "policy-ar4": "",
            "policy-ar4-main1": "",
            "policy-ar4-main2": "",
            "policy-ar5": "",
            "policy-ar5-main1": "",
            "policy-ar5-main2": "",
            "policy-ar5-main3": "",
            "policy-ar5-main4": "",
            "policy-ar5-main5": "",
            "policy-ar6": "",
            "policy-ar6-main1": "",
            "policy-ar6-main2": "",
            "policy-ar6-main3": "",
            "policy-ar6-main4": "",
            "policy-ar6-main5": "",
            "policy-ar7": "",
            "policy-ar7-main": "",
            "policy-ar7-t1": "",
            "policy-ar7-t2": "",
            "policy-ar7-t3": "",
            "policy-ar7-t4": "",
            "policy-ar7-sub1": "",
            "policy-ar7-sub2": "",
            "policy-ar7-sub3": "",
            "policy-ar7-sub4": "",
            "policy-ar7-sub5": "",
            "policy-ar7-sub6": "",
            "policy-ar7-sub7": "",
            "policy-ar7-sub8": "",
            "policy-ar7-sub9": "",
            "policy-ar7-sub10": "",
            "policy-ar8": "",
            "policy-ar8-main1": "",
            "policy-ar8-main2": "",
        },
    },

    "/html/gamepage.html": {
        "ko": {
            "info-title": "곰팡이 키우기",
            "info-text": "메인 텍스트",
        },
        "en": {
            "info-title": "Mold Farm",
            "info-text": "main text",
        },
    },
}