const data = {
    "/index.html": {
        "ko": {
            "moldtitle": "곰팡이 키우기",
            "about-sub": "시너지의 폭발",
            "about-text":
                "Hyper Hole는 게임 제작의 중심에서 최고의 창의력을 끌어내는 스튜디오입니다. 다양한 기술이 조합되어 빅뱅을 일으키듯, Hyper Hole은 팀워크를 통해 놀라운 게임을 탄생시킵니다. 우리는 우주의 퀘이사처럼 빛나는 게임을 만들기 위해, 초거대 블랙홀처럼 강력한 협업을 추구합니다. Hyper Hole에서 모든 팀원이 하나 되어 최고의 게임을 창조합니다.",
            "maintext": "퀘이사는 격렬히 폭발하지만 모든것을 빨아들이는 블랙홀이 그 폭발력의 원천입니다. Hyper Hole의 로고는 퀘이사의 에너지가 뿜어지는 모습과 안을 향해 빨아들여지는 질량을 형상화하여 다양한 기술의 시너지, 조합이 폭발하는 모습을 표현하였습니다.",
            "gametext": "Hyper Hole는 게임 제작의 중심에서 최고의 창의력을 끌어내는 스튜디오입니다. 다양한 기술이 조합되어 빅뱅을 일으키듯, Hyper Hole은 팀워크를 통해 놀라운 게임을 탄생시킵니다. ",
            "phone": "phone: 031-332-9990",
        },
        "en": {
            "moldtitle": "Mold Farm",
            "about-sub": "explosion of synergy",
            "about-text":
                "Hyper Hole is a studio that brings out the best creativity at the heart of game development. Just as various substances combine to create the Big Bang, Hyper Hole brings together diverse individuals to create amazing games. To create games that shine like quasars in the universe, we pursue powerful collaboration, like a supermassive black hole. At Hyper Hole, every team member unites to create the best games.",
            "maintext": "Quasars erupt violently, but the source of this explosive power is a black hole that absorbs everything. The logo of Hyper Hole symbolizes the energy emitted by a quasar and the mass being drawn inward, expressing the explosive synergy and combination of various technologies.",
            "gametext": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magn",
            "phone": "phone: +82); 31-332-9990",
        },
    },

    "/html/privacypolicy.html": {
        "ko": {
            "pp_title": "개인정보 처리방침",
            "policy-intro": "",
            "policy-ar1": "",
            "policy-ar1-main": "",
            "policy-ar1-sub": "",
            "policy-ar2": "",
            "policy-ar2-main": "",
            "policy-ar2-sub1": "",
            "policy-ar2-sub2": "",
            "policy-ar2-sub3": "",
            "policy-ar2-sub4": "",
            "policy-ar3": "",
            "policy-ar3-main1": "",
            "policy-ar3-main2": "",
            "policy-ar3-main3": "",
            "policy-ar3-main4": "",
            "policy-ar3-main5": "",
            "policy-ar3-main6": "",
            "policy-ar3-main7": "",
            "policy-ar3-main8": "",
            "policy-ar3-main9": "",
            "policy-ar4": "",
            "policy-ar4-main1": "",
            "policy-ar4-main2": "",
            "policy-ar5": "",
            "policy-ar5-main1": "",
            "policy-ar5-main2": "",
            "policy-ar5-main3": "",
            "policy-ar5-main4": "",
            "policy-ar5-main5": "",
            "policy-ar6": "",
            "policy-ar6-main1": "",
            "policy-ar6-main2": "",
            "policy-ar6-main3": "",
            "policy-ar6-main4": "",
            "policy-ar6-main5": "",
            "policy-ar7": "",
            "policy-ar7-main": "",
            "policy-ar7-t1": "",
            "policy-ar7-t2": "",
            "policy-ar7-t3": "",
            "policy-ar7-t4": "",
            "policy-ar7-sub1": "",
            "policy-ar7-sub2": "",
            "policy-ar7-sub3": "",
            "policy-ar7-sub4": "",
            "policy-ar7-sub5": "",
            "policy-ar7-sub6": "",
            "policy-ar7-sub7": "",
            "policy-ar7-sub8": "",
            "policy-ar7-sub9": "",
            "policy-ar7-sub10": "",
            "policy-ar8": "",
            "policy-ar8-main1": "",
            "policy-ar8-main2": "",
        },

        "en": {
            "pp_title": "Personal Information Collection Policy",
            "policy-intro": "",
            "policy-ar1": "",
            "policy-ar1-main": "",
            "policy-ar1-sub": "",
            "policy-ar2": "",
            "policy-ar2-main": "",
            "policy-ar2-sub1": "",
            "policy-ar2-sub2": "",
            "policy-ar2-sub3": "",
            "policy-ar2-sub4": "",
            "policy-ar3": "",
            "policy-ar3-main1": "",
            "policy-ar3-main2": "",
            "policy-ar3-main3": "",
            "policy-ar3-main4": "",
            "policy-ar3-main5": "",
            "policy-ar3-main6": "",
            "policy-ar3-main7": "",
            "policy-ar3-main8": "",
            "policy-ar3-main9": "",
            "policy-ar4": "",
            "policy-ar4-main1": "",
            "policy-ar4-main2": "",
            "policy-ar5": "",
            "policy-ar5-main1": "",
            "policy-ar5-main2": "",
            "policy-ar5-main3": "",
            "policy-ar5-main4": "",
            "policy-ar5-main5": "",
            "policy-ar6": "",
            "policy-ar6-main1": "",
            "policy-ar6-main2": "",
            "policy-ar6-main3": "",
            "policy-ar6-main4": "",
            "policy-ar6-main5": "",
            "policy-ar7": "",
            "policy-ar7-main": "",
            "policy-ar7-t1": "",
            "policy-ar7-t2": "",
            "policy-ar7-t3": "",
            "policy-ar7-t4": "",
            "policy-ar7-sub1": "",
            "policy-ar7-sub2": "",
            "policy-ar7-sub3": "",
            "policy-ar7-sub4": "",
            "policy-ar7-sub5": "",
            "policy-ar7-sub6": "",
            "policy-ar7-sub7": "",
            "policy-ar7-sub8": "",
            "policy-ar7-sub9": "",
            "policy-ar7-sub10": "",
            "policy-ar8": "",
            "policy-ar8-main1": "",
            "policy-ar8-main2": "",
        },
    },

    "/html/gamepage.html": {
        "ko": {
            "info-title": "곰팡이 키우기",
            "info-text": "메인 텍스트",
        },
        "en": {
            "info-title": "Mold Farm",
            "info-text": "main text",
        },
    },
}